### ISSUE TITLE
Update the NuGet Package version to 0.8

### ISSUE THREAD

**Issue by alloncm** [kaitai-io/kaitai_struct_csharp_runtime#18]
Hi Im currently trying to learn how to use this awesome tool and I have noticed that the version of the NuGet package available is 0.7 where version 0.8 exists.
Could you please upload the latest version?

**Comment by Arlorean** [comment]
I think the .nuspec file has been removed but you could probably create a pull request to put it back in. I think it can be published directly from the kaitai-io/kaitai_struct_csharp_runtime repository now if this is in place.

Here's the one I created a while back for the first nuget package that I published from my personal nuget account:
https://github.com/Arlorean/kaitai_struct_csharp_runtime/blob/master/kaitai_struct_runtime_csharp.nuspec

**Comment by alloncm** [comment]
Hi since the project is now targeting .net standard and uses the .net SDK I'm pretty sure there is no need anymore to add a .nuspec file in order to publish the package you just need to pack it (using the pack command ) and than publish the generated .nupkg file (https://docs.microsoft.com/en-us/nuget/reference/nuspec)
I just think it will be better if the original author of the package will publish the next version and not me.

**Comment by alloncm** [comment]
@Arlorean  Hi could you please comment when you done uploading the new version? (since you are the original author of the package It will be better if you will update it (new version to the existing one and not another new package)).
If for some reason you cant (or don't want to) upload the new version please let me know and I will upload it myself.
Thanks for all the work 😄

**Comment by Arlorean** [comment]
OK. I have some time this weekend. I'll see if I can upload the latest version. Sorry for the delay.
**Edit:** OK this should be done now. Let me know if you get any issues with the new [0.8 nuget package](https://www.nuget.org/packages/KaitaiStruct.Runtime.CSharp/0.8.0).
**Another Edit:** Do you want me to create a pull request to update the version number to 0.9.0?

**Comment by alloncm** [comment]
It will really help (I think...)
Any way thank you very much.

**Comment by GreyCat** [comment]
0.9 (neither compiler, nor runtimes) were officially released. Please don't publish relevant nugets yet.
