### ISSUE TITLE
Relicense or dual-license under MIT too

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_csharp_runtime#3]
I've noticed that @indrora originally applied Apache to his contribution, and all our subsequent commits thus were also Apache-licensed.

There is a problem with [Apache license being incompatible with GPLv2](https://www.gnu.org/licenses/license-list.en.html#apache2), thus this license choice can potentially impede adoption of Kaitai Struct for free/open source projects which still use GPLv2.

The majority of other runtimes are MIT-licensed, so could I persuade you all to switch to MIT?

**Comment by LogicAndTrick** [comment]
Yep, I'm all for MIT license. If it matters, I didn't know there was a C# runtime already when I wrote the `BinaryReader`-based runtime, so it's not a derivative work. I guess it's a bit of a grey area because it's merged over the top of the original implementation.

**Comment by indrora** [comment]
Fixed. Since I wrote the original implementation, I'll just say "If we need to make it MIT, let's make it MIT."

**Comment by GreyCat** [comment]
Thanks! So be it :)

I've currently in the middle of releasing v0.4, will fix info on license shortly.
