### ISSUE TITLE
Nested regions in source

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_csharp_runtime#4]
I'm trying to get all runtimes to use uniform order of methods and sectioning. Can you enlighten me if C#'s `#region` / `#endregion` can be nested?

I.e. I'd like to use something like (indented for the sake of illustration, won't be indented in real code):

``` cs
#region Integer types
  #region Signed
    #region Big-endian
    #endregion
    #region Little-endian
    #endregion
  #endregion
...
#endregion
```

I guess that it's valid from compiler's POV, and, so far I've checked that:
- it works flawlessly in KWrite/Kate (i.e. regions/subregions get properly folded)
- it kind of works in MonoDevelop (only top-level regions are seen in document's structure view, and MonoDevelop does not seem to support folding at all)
- Doxygen does not support nested regions properly, and thus messes up "group names" — but, anyway, probably Doxygen is _not_ a documentation generator of choice for C#?

Could you check if that would be ok with Visual Studio editor? What about major documentation generation tools?

**Comment by LogicAndTrick** [comment]
Yes, VS supports nested regions. Though personally I find any nesting level more than 1 to be annoying to navigate. My preference is usually to avoid nesting groups.

The .NET compiler is the only documentation tool I've used (it generates a clean XML file for any consumer to use), and it ignores regions. I've not used HTML doc generators with .NET before, most libraries ship with just the compiled DLL and the matching XML file.

**Comment by GreyCat** [comment]
Ok, thanks!

The whole KS runtime thing is not really the easiest one to navigate anyway - there's _lots_ of repetitive code with very subtle differences and, unfortunately, it's the way to go. It has to be _somewhere_ anyway. So, basically, the question is not if we want nested regions or not — they are already there, that's objective reality that there are 3 levels of hierarchy in `read_u4be`-like stuff - i.e. `u`, `4` and `be`. The question is whether it's ok to use language-supplied formatting for regions or resort to fancy ASCII-art comments like these:

``` ruby
  # ========================================================================
  # Integer numbers
  # ========================================================================

  # ------------------------------------------------------------------------
  # Signed
  # ------------------------------------------------------------------------

  # ........................................................................
  # Big-endian
  # ........................................................................
```

IMHO, it's better to use regions if there is support for them.

**Comment by LogicAndTrick** [comment]
A hybrid approach could work as well, using regions for the first level of grouping and then just comments after that:

``` cs
#region Integers

....

// 16 bit integers

short ReadS2le() { ... }
short ReadS2be() { ... }
ushort ReadU2le() { ... }
ushort ReadU2be() { ... }

...

#endregion
```

Another option could be to break the groups up a bit more:

``` cs
#region 8 bit integers

...

#endregion

#region 16 bit integers

short ReadS2le() { ... }
short ReadS2be() { ... }
ushort ReadU2le() { ... }
ushort ReadU2be() { ... }

#endregion

... etc ...
```

**Comment by GreyCat** [comment]
The order and grouping is more or less already've been decided, as outlined in https://github.com/kaitai-io/kaitai_struct/blob/master/runtime/README.md — and there is a some kind of a rationale behind it. 

For example, it makes sense to do "signed" vs "unsigned" branching at the top of the hierarchy due to languages like Java treating "signed" integers as first-class citizens and all "unsigned" stuff going through somewhat different and sometimes quite messy type aliasing / upcasting process. From a ordering perspective (for example, while porting runtime to new target language), it's much easier to observe 1-2-4-8 progression by hand and rely on the more ambiguous signed/unsigned and big-/little-endian structure being already set in stone by a region layout copied from verbatim source, than to do it vice versa - when you've only got "8-bit integers", "16-bit integers", "32-bit integers" copied from the region layout and then you have to memorize (or keep looking up every time) in which order you would need to put your 4 methods to keep it consistent.

Of course, it is possible to discuss and change it, but it would require changing it everywhere :)

**Comment by LogicAndTrick** [comment]
Nah, your reasoning makes sense. No nested groups is still my vote (i.e. one level, and then comments/ascii art), but it's fine either way really. Extra regions are easy to ignore, and the existing runtime code likely won't need much maintenance anyway.

How about skipping a level and grouping at level 2? Like:

```
#region Signed integers

...

#endregion

#region Unsigned integers

...

#endregion

```

**Comment by GreyCat** [comment]
Ok, let's settle for the uniformity for now, as I've really eager to finally get that v0.4 release out :)

Removing extra level of nesting might be a good idea — but let's postpone it for later.
