### ISSUE TITLE
FileStream implicit restriction

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct_csharp_runtime#8]
Some parts of the code implicitly depend on the stream being seekable and tellable, like FileStream. Arbitrary streams (like pipes?) may be non-seekable and non-tellable. Either clarify in documentation that such a restrition exists, or change the code somehow.
```csharp
public bool IsEof
{
    get { return BaseStream.Position >= BaseStream.Length; }
}
public long Size
{
    get { return BaseStream.Length; }
}

```

**Comment by GreyCat** [comment]
Majority of KaitaiStream implementations require underlying streams to be seekable and able to tell its position. I don't know if .NET `Stream` could be non-seekable — but if it could be, then it's actually even cooler — this way you *can* use KS even on pipes / sockets, but it will fail only if you'll use something that would require seeks (i.e. parse instances).

Indeed, that warrants some documentation. http://doc.kaitai.io/lang_csharp.html ?

**Comment by arekbulski** [comment]
I should point for completeness, that there are few pieces of code there that could be implemented without seeks, likea reading until EOF. I am not able to produce specific lines atm.

**Comment by arekbulski** [comment]
PipeStream has these two:
- Length, always throws error
https://msdn.microsoft.com/en-us/library/system.io.pipes.pipestream.length(v=vs.110).aspx
- CanSeek, always false
https://msdn.microsoft.com/en-us/library/system.io.pipes.pipestream.canseek(v=vs.110).aspx

**Comment by GreyCat** [comment]
Well, probably we should throw in a few tests for that as well then — i.e. some special handling that would construct such an underlying stream and try to run certain ksy on top of that. Probably Python can do something like that too?

**Comment by arekbulski** [comment]
I was just about to mention it, Python runtime checks eof by reading one byte.
https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/master/kaitaistruct.py#L63

**Comment by GreyCat** [comment]
Yeah, it's the same problem with semantics of EOF-like check :( There are two versions of them: (1) EOF means that we are standing at end of file, (2) EOF means we've tried to read past the end-of-file at least once and hit an error.

Python, unfortunately, follows (2), so we had to emulate (1).

**Comment by arekbulski** [comment]
Is there an actual test case where these 2 semantics produce different results? I would not mind if different runtimes implemented EOF check with different semantics, as long as its properly documented, and there are no test cases producing different results.

**Comment by GreyCat** [comment]
For example, given 1-byte input stream, this would return different results:

```yaml
meta:
  id: test
seq:
  - id: foo
    type: u1
instances:
  is_eof: _io.eof
```

Using semantics (1) `is_eof` would be true, using semantics (2) `is_eof` would just return false. So, no, using semantics (2) is a bad choice for KS. It would be *much* harder to implement declarative data model if we'll be dealing with "error-during-read-to-get-EOF-is-normal" world.

**Comment by arekbulski** [comment]
Then you need to make a call for the project. Just say so, and I will change Python runtime to (1) semantics.

**Comment by arekbulski** [comment]
Would this be equivalent example? Parsing 0 byte stream.

```yaml
seq:
instances:
  is_eof: _io.eof
```

**Comment by arekbulski** [comment]
Note that with (1) semantics, we wont be able to parse several types which may be neck breaking for many examples. I will review the 2 runtimes later for that.

**Comment by GreyCat** [comment]
> Just say so, and I will change Python and C# runtimes to (1) semantics.

All existing runtimes already use (1) semantics. No need to do anything. I'm just explaining why Python implementation is more complicated.

> Would this be equivalent example?

Yeah, but you should omit `seq:` totally, or it won't be legal YAML.

> Note that with (1) semantics, we wont be able to parse several types which may be neck breaking for many examples.

What exactly do you mean by being "able to parse several types"?

**Comment by arekbulski** [comment]
Python runtime currently implements (2). 
https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/master/kaitaistruct.py#L63

Moreover, some methods, despite not calling `is_eof()`, also implement (2) semantics.
https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/master/kaitaistruct.py#L248

**Comment by GreyCat** [comment]
Ok, we're actually talking about the same thing, but it's a matter of terminology.

That's exactly because of [that code](https://github.com/kaitai-io/kaitai_struct_python_runtime/blob/master/kaitaistruct.py#L63-L70) Python provides (1) semantics to end-user, hiding the fact that underlying stream uses native Python semantics, which is (2).

Methods like `read_bytes_term` behave the same in all languages. Again, inside it is more efficient to use native Python approach, which uses (2) semantics, but what is important is the result for end user.

**Comment by arekbulski** [comment]
Then maybe this method should have different impl: instead of read(1) do tell()->seek(0,from end)->tell()->compare positions?

**Comment by GreyCat** [comment]
I'm not sure:

(1) this might be slower or faster, ideally, we'll need to benchmark
(2) seek-to-end procedure might be implemented using `stat()`-like call, which relies on a file size reported by an OS, which might be fake for virtual files / file being appended to while we read them.

**Comment by arekbulski** [comment]
Agreed, we need some note in documentation. Working on it.

**Comment by arekbulski** [comment]
Further suggestions should be directed into PR.
